apiVersion: v1
kind: Service
metadata:
  name: alpha-service
spec:
  selector:
    app: alpha-app
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: alpha-pod
  labels:
    app: alpha-app
spec:
  containers:
  - name: alpha-bash
    image: bash
    command: ['sh', '-c', 'echo alpha-bash container started && sleep 600']
  - name: alpha-nginx
    image: nginx

